// Generated by scripts/map/render-svg.mjs from data/map/. Do not edit by hand.

import type { NearshoreFacts } from "./mapSvg.js";

export const MAP_FACTS: NearshoreFacts = {
  "width": 1000,
  "height": 346.2,
  "jetties": 51,
  "streetLabels": [
    116,
    110,
    100,
    90,
    67,
    60,
    50
  ],
  "depthsFt": [
    2,
    4,
    6,
    8,
    10,
    12,
    14,
    16,
    18,
    20,
    30,
    40
  ],
  "survey": "Surveyed May 2023 (47% of the surf zone); older parts 2009, 2013 and 2017",
  "sources": [
    {
      "name": "NOAA BlueTopo (National Bathymetric Source)",
      "url": "https://noaa-ocs-nationalbathymetry-pds.s3.amazonaws.com/index.html#BlueTopo/",
      "license": "Public domain (U.S. Government work); contributor surveys are CC0-1.0 per the tile attribute tables",
      "attribution": "NOAA Office of Coast Survey, National Bathymetric Source (BlueTopo)",
      "retrieved": "2026-10-04",
      "surveyDates": "Nearshore cells (0 to about 37 ft below MLLW, ocean side): 47% USGS multibeam E00998, 2023-05-06 to 2023-05-16; 18% NOAA H12604/H12891, 2013-09 to 2013-12; 17% NOAA H11710/H12138, 2009-10 to 2009-11; 9% USACE JALBTCX topobathy lidar, 2017-08 to 2017-09; about 8% other USACE and NOAA surveys 2014 to 2026-06; about 1% legacy chart data dated 1807 to 1950. Shares are from the Contributor band and its attribute table, sampled over the box."
    },
    {
      "name": "NOAA NCEI Continuously Updated DEM (CUDEM), 1/9 arc-second topobathy",
      "url": "https://noaa-nos-coastal-lidar-pds.s3.amazonaws.com/dem/NCEI_ninth_Topobathy_2014_8483/northeast_sandy/ncei19_n40x75_w074x00_2015v1.tif",
      "license": "Public domain (U.S. Government work)",
      "attribution": "NOAA National Centers for Environmental Information, CUDEM",
      "retrieved": "2026-10-04",
      "surveyDates": "Unknown per cell: the tile has no source or date band. The 2015 tile was built from post-Hurricane Sandy topographic lidar and older hydrographic surveys, so the land surface is about 2014 or earlier."
    },
    {
      "name": "NOAA VDatum tidal datum conversion",
      "url": "https://vdatum.noaa.gov/vdatumweb/api/convert?s_x=-73.86&s_y=40.57&s_z=0&s_h_frame=NAD83_2011&s_coor=geo&s_v_frame=NAVD88&s_v_unit=m&t_h_frame=NAD83_2011&t_v_frame=MLLW&t_v_unit=m&region=contiguous",
      "license": "Public domain (U.S. Government work)",
      "attribution": "NOAA National Ocean Service, VDatum",
      "retrieved": "2026-10-04",
      "surveyDates": "Not applicable: a datum model, not a survey."
    },
    {
      "name": "OpenStreetMap",
      "url": "https://www.openstreetmap.org/copyright",
      "license": "ODbL 1.0",
      "attribution": "© OpenStreetMap contributors",
      "retrieved": "2026-10-04",
      "surveyDates": null
    }
  ],
  "bounds": [
    -73.9044,
    40.5402,
    -73.7606,
    40.5969
  ]
};
